version: "3.9"
services:
  scouting-app:
    restart: always
    build: .
    ports:
      - "4173:4173"
    depends_on:
      - scouting-app-backend
    networks:
      frontend:
        ipv4_address: 172.46.7.4

  scouting-app-backend:
    restart: always
    build: backend/.
    ports:
      - "5173:5173"
    depends_on:
      scouting-app-backend-gate:
        condition: service_completed_successfully 
    networks:
      frontend:
        ipv4_address: 172.46.7.3


  scouting-app-backend-gate:
    restart: "no"
    build: backend/.
    command: ["node", "gate.js"]
    depends_on:
      - mysql
    networks:
      frontend:
        ipv4_address: 172.46.7.3

  mysql:
    image: "mysql"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: FRC4607CIS
      MYSQL_DATABASE: scouting
    volumes:
      - type: bind
        source: ./backend/db
        target: /var/lib/mysql
    networks:
      frontend:
        ipv4_address: 172.46.7.2
  
networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.46.7.0/24
        gateway: 172.46.7.1