/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * One or more scouting entries uploaded by a scouter
 */
export type ScoutingEntryUploadSchema = ScoutingEntryUploadSchema1 & ScoutingEntryUploadSchema2;
export type ScoutingEntryUploadSchema1 = {
  [k: string]: unknown;
};

export interface ScoutingEntryUploadSchema2 {
  /**
   * The table to insert the request into
   */
  title: "pits" | "matches" | "ranking";
  [k: string]: unknown;
}
