/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A single match scouting entry in the database
 */
export interface MatchScoutEntryInterface {
  event_key: string;
  match_level: number;
  match_number: number;
  is_blue: boolean;
  ds_position: number;
  team_number: number;
  scouter_name: string;
  starting_pos: number;
  auto_fuel: number;
  auto_climb: boolean;
  cycles: number;
  fuel_score: number;
  passing: boolean;
  climb: number;
  zone_play: number;
  bump_rank: number;
  drive_rank: number;
  defense_rank: number;
  breakdown: boolean;
  comments: string;
  scouted_time: string;
}
