/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A single match scouting entry in the database
 */
export interface MatchScoutEntryInterface {
  event_key: string;
  match_level: number;
  match_number: number;
  is_blue: boolean;
  ds_position: number;
  team_number: number;
  scouter_name: string;
  starting_pos: number;
  mobility: boolean;
  defense: boolean;
  comments: string;
  ScoutedTime: string;
  Level1: number;
  Level2: number;
  Level3: number;
  Level4: number;
  auto_algae: number;
  tele_algae: boolean;
  tele_Level1: number;
  tele_Level2: number;
  tele_Level3: number;
  tele_Level4: number;
  robo_barge_score: number;
  processor_scored: number;
  climb: number;
  driver_rank: number;
  breakdown: boolean;
}
