/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A single pit scouting entry in the database
 */
export interface PitScoutEntryInterface {
  event_key: string;
  scouter_name: string;
  team_number: number;
  prog_lang: number;
  bat_brand: number;
  other_brand: string;
  num_bat: number;
  bat_condition: string;
  height: number;
  hopper: boolean;
  hopper_size: number;
  spare_parts: boolean;
  bump: boolean;
  trench: boolean;
  shoot_type: number;
  shoot_notes: string;
  climb_type: number;
  climb_notes: string;
  index_type: number;
  index_notes: string;
  feed_rate: number;
  intake: number;
  intake_speed: number;
  pre_checklist: boolean;
  not_breakdown: string;
  components_protected: boolean;
  breaker_cover: boolean;
  pic_robot_full: string;
  pic_drivetrain: string;
  pic_intake: string;
  pic_shooter: string;
  pic_climber: string;
  pic_electronics: string;
  pic_battery: string;
  pic_battery_charging: string;
  pic_misc: string;
  scouted_time: string;
}
