/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A single pit scouting entry in the database
 */
export interface PitScoutEntryInterface {
  scouter_name: string;
  team_number: number;
  length: number;
  width: number;
  weight?: number;
  start_height: number;
  max_height: number;
  dt_type: number;
  drive_motor: number;
  swerve_type: number;
  wheel_rep_freq: string;
  bumper_height: number;
  can_bus_top: number;
  pneumatics: boolean;
  programming_language: number;
  num_batt: number;
  does_batt_maint: boolean;
  batt_maint_txt: string;
  batt_testing: boolean;
  batt_brand: number;
  batt_needed: boolean;
  spare_parts: boolean;
  pit_checklist: boolean;
  does_scouting: boolean;
  trade_scouting_data: boolean;
  batt_storchrg: string;
  batt_loc: string;
  batt_con: string;
  powersw_loc: string;
  radio_loc: string;
  misc_pics: string;
  comments: string;
  ScoutedTime: string;
}
